### ISSUE TITLE
panic: certificate worker: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/interactsh#412]
### Interactsh version:
main / dev

### Current Behavior:
```console
2022/11/24 09:10:38 panic: certificate worker: runtime error: invalid memory address or nil pointer dereference
goroutine 121 [running]:
github.com/caddyserver/certmagic.(*jobManager).worker.func1()
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:58 +0x65
panic({0xb05b20, 0x159a890})
        /snap/go/9991/src/runtime/panic.go:838 +0x207
github.com/caddyserver/certmagic.(*Config).renewCert.func2({0x11add98, 0xc0006942d0})
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:821 +0xc14
github.com/caddyserver/certmagic.doWithRetry({0x11add28, 0xc0001a4048}, 0x0, 0xc0008d3b60)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:106 +0x1cb
github.com/caddyserver/certmagic.(*Config).renewCert(0xc0001ce370, {0x11add28, 0xc0001a4048}, {0xc0000361e2, 0xb}, 0x0, 0x0)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:860 +0x58b
github.com/caddyserver/certmagic.(*Config).RenewCertAsync(...)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:690
github.com/caddyserver/certmagic.(*Config).manageOne.func2()
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:394 +0x20c
github.com/caddyserver/certmagic.(*jobManager).worker(0x159dba0)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:73 +0x112
created by github.com/caddyserver/certmagic.(*jobManager).Submit
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:50 +0x28a
2022/11/24 09:10:40 panic: certificate worker: runtime error: invalid memory address or nil pointer dereference
goroutine 82 [running]:
github.com/caddyserver/certmagic.(*jobManager).worker.func1()
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:58 +0x65
panic({0xb05b20, 0x159a890})
        /snap/go/9991/src/runtime/panic.go:838 +0x207
github.com/caddyserver/certmagic.(*Config).renewCert.func2({0x11add98, 0xc000598630})
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:821 +0xc14
github.com/caddyserver/certmagic.doWithRetry({0x11add28, 0xc0001a4048}, 0x0, 0xc00082bb60)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:106 +0x1cb
github.com/caddyserver/certmagic.(*Config).renewCert(0xc0001ce370, {0x11add28, 0xc0001a4048}, {0xc0000361e0, 0xd}, 0x0, 0x0)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:860 +0x58b
github.com/caddyserver/certmagic.(*Config).RenewCertAsync(...)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:690
github.com/caddyserver/certmagic.(*Config).manageOne.func2()
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/config.go:394 +0x20c
github.com/caddyserver/certmagic.(*jobManager).worker(0x159dba0)
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:73 +0x112
created by github.com/caddyserver/certmagic.(*jobManager).Submit
        /root/go/pkg/mod/github.com/caddyserver/certmagic@v0.17.1/async.go:50 +0x28a
2022/11/24 09:10:42 [ERROR] Keeping lock file fresh: open /root/.local/share/certmagic/locks/issue_cert_wildcard_.interact.sh.lock: too many open files - terminating lock maintenance (lockfile: /root/.local/share/certmagic/locks/issue_cert_wildcard_.interact.sh.lock)
2022/11/24 09:10:42 [ERROR] Keeping lock file fresh: open /root/.local/share/certmagic/locks/issue_cert_interact.sh.lock: too many open files - terminating lock maintenance (lockfile: /root/.local/share/certmagic/locks/issue_cert_interact.sh.lock)
```

### Expected Behavior:
no panic

**Comment by Mzack9999** [comment]
@ehsandeep The panic is recovered internally and this is only a console message error (ref: https://github.com/caddyserver/certmagic/blob/7d6aa77b24e7db20b466766e5e414bbeb4ad9b61/async.go#L59)
